### ISSUE TITLE
Filter out users without contact details

### ISSUE THREAD

**Issue by yezooz** [linusnorton/dev-sourcr#1]
I'm quite lonely person and use this tool to find new friends in my area, sometimes it's really hard to get in touch with people if they don't put their email address or website. Tried sending info about me via pull requests to their repos, but usually it's not very successful method. I was even called weirdo couple of times, it really hurt my feelings. It's not your fault, but would be much easier if could add option to hide all people without contact details.

Love this tool, thanks for all the hard work!

**Comment by linusnorton** [comment]
Export now excludes anyone without an email address. In future maybe it would be better to give the option to deselect individuals when exporting.
